server:
  port: 9004

spring:
  application:
    name: rest-api
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  datasource:
    url: jdbc:postgresql://postgres:5432/data-db
    username: postgres
    password: 123456
    driverClassName: org.postgresql.Driver
