server:
  port: 9002

spring:
  application:
    name: stream-reader
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/data-db
    username: postgres
    password: 123456
    driverClassName: org.postgresql.Driver

kafka:
  bootstrapAddress: localhost:9092
